# Generated by Django 4.2.5 on 2023-09-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="day",
            field=models.CharField(
                choices=[
                    ("Mon", "Monday"),
                    ("Tues", "Tuesday"),
                    ("Wed", "Wednesday"),
                    ("Thurs", "Thursday"),
                    ("Fri", "Friday"),
                    ("Sat", "Saturday"),
                    ("Sun", "Sunday"),
                ],
                default="Mon",
                max_length=5,
            ),
        ),
    ]
