# Generated by Django 4.2.5 on 2023-09-20 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0002_alter_route_day"),
    ]

    operations = [
        migrations.RenameField(
            model_name="village",
            old_name="main_index",
            new_name="sub_index",
        ),
    ]
