# Generated by Django 4.2.5 on 2023-09-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0003_rename_main_index_village_sub_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="directions",
            name="village",
        ),
        migrations.AddField(
            model_name="directions",
            name="village",
            field=models.ManyToManyField(related_name="villages", to="mail.village"),
        ),
    ]
