# Generated by Django 4.2.5 on 2023-09-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0004_remove_directions_village_directions_village"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directions",
            name="village",
            field=models.ManyToManyField(
                null=True, related_name="villages", to="mail.village"
            ),
        ),
    ]
