# Generated by Django 4.2.5 on 2023-09-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0007_alter_directions_village"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Mon", "Monday"),
                            ("Tues", "Tuesday"),
                            ("Wed", "Wednesday"),
                            ("Thurs", "Thursday"),
                            ("Fri", "Friday"),
                            ("Sat", "Saturday"),
                            ("Sun", "Sunday"),
                        ],
                        default="Mon",
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="route",
            name="day",
        ),
        migrations.AddField(
            model_name="route",
            name="day",
            field=models.ManyToManyField(related_name="routs", to="mail.day"),
        ),
    ]
