# Generated by Django 4.2.5 on 2023-10-07 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0008_day_remove_route_day_route_day"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="day",
            options={"ordering": ("day",)},
        ),
        migrations.AlterModelOptions(
            name="village",
            options={"ordering": ("title",)},
        ),
    ]
